apiVersion: v1
kind: ConfigMap
metadata:
  name: acacia360-maintenance-config
  labels:
    app: acacia360-maintenance-app

data:
  nginx.conf: |
    server {
      listen 8085;
      server_name _;

      root /usr/share/nginx/html;
      index index.html;

      # Static files
      location /assets/ {
          try_files $uri =404;
          expires max;
          access_log off;
      }

      location /static/ {
          try_files $uri =404;
          expires max;
          access_log off;
      }

      location ~* \.(?:js|css|png|jpg|jpeg|gif|ico|svg|woff2?|ttf|eot)$ {
          try_files $uri =404;
          expires max;
          access_log off;
      }

      # React Native Web / Expo SPA fallback
      location / {
          try_files $uri $uri/ /index.html;
      }
    }