apiVersion: apps/v1
kind: Deployment
metadata:
  name: acacia360-maintenance-app
  labels:
    app: acacia360-maintenance-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: acacia360-maintenance-app

  template:
    metadata:
      labels:
        app: acacia360-maintenance-app

    spec:
      containers:
        - name: acacia360-maintenance-app

          image: acaciagreentechnologies/acacia360-maintenance:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8085

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "250m"

          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
              readOnly: true

      volumes:
        - name: nginx-config-volume
          configMap:
            name: acacia360-maintenance-config
            items:
              - key: nginx.conf
                path: nginx.conf