// src/config/env.js
import { BASE_API_URL, TASK_SERVICE_API_PORT , ROOM_SERVICE_API_PORT,USER_SERVICE_API_PORT,AUTH_SERVICE_API_PORT,NOTIFICATION_SERVICE_API_PORT} from '@env';
// export const TASK_SERVICE_API_URL = `${BASE_API_URL}:${TASK_SERVICE_API_PORT}/api`;
// export const ROOM_SERVICE_API_URL = `${BASE_API_URL}:${ROOM_SERVICE_API_PORT}/api`;
// export const USER_SERVICE_API_URL = `${BASE_API_URL}:${USER_SERVICE_API_PORT}/api`;
// export const AUTH_SERVICE_API_URL = `${BASE_API_URL}:${AUTH_SERVICE_API_PORT}/api`;
// export const NOTIFICATION_SERVICE_API_URL = `${BASE_API_URL}:${NOTIFICATION_SERVICE_API_PORT}/notifications`;
// export const PORTFOLIO_SERVICE_API_URL = `${BASE_API_URL}:${PORTFOLIO_SERVICE_API_PORT}/api`;
// export const PROPERTY_SERVICE_API_URL = `${BASE_API_URL}:${PROPERTY_SERVICE_API_PORT}/api`;
// export const BOILER_SERVICE_API_URL = `${BASE_API_URL}:${BOILER_SERVICE_API_PORT}/api`;
// export const FLOW_METER_SERVICE_API_URL = `${BASE_API_URL}:${FLOW_METER_SERVICE_API_PORT}/api`;
// export const SENSOR_SERVICE_API_URL = `${BASE_API_URL}:${SENSOR_SERVICE_API_PORT}/api`;
// export const WATER_PUMP_SERVICE_API_URL = `${BASE_API_URL}:${WATER_PUMP_SERVICE_API_PORT}/api`;
// export const GRAPHICS_SERVICE_API_URL = `${BASE_API_URL}:${GRAPHICS_SERVICE_API_PORT}/api`;


//:: DEPLOYMENT URL :://
export const TASK_SERVICE_API_URL = `${BASE_API_URL}/api`;
export const ROOM_SERVICE_API_URL = `${BASE_API_URL}/api`;
export const USER_SERVICE_API_URL = `${BASE_API_URL}/api`;
export const AUTH_SERVICE_API_URL = `${BASE_API_URL}/api`;
export const NOTIFICATION_SERVICE_API_URL = `${BASE_API_URL}/notifications`;
export const PORTFOLIO_SERVICE_API_URL = `${BASE_API_URL}/api`;
export const PROPERTY_SERVICE_API_URL = `${BASE_API_URL}/api`;
export const BOILER_SERVICE_API_URL = `${BASE_API_URL}/api`;
export const FLOW_METER_SERVICE_API_URL = `${BASE_API_URL}/api`;
export const SENSOR_SERVICE_API_URL = `${BASE_API_URL}/api`;
export const WATER_PUMP_SERVICE_API_URL = `${BASE_API_URL}/api`;
export const GRAPHICS_SERVICE_API_URL = `${BASE_API_URL}/api`;
