// src/config/env.js
import { API_URL, TASK_SERVICE_API_PORT , ROOM_SERVICE_API_PORT,USER_SERVICE_API_PORT,AUTH_SERVICE_API_PORT,NOTIFICATION_SERVICE_API_PORT} from '@env';
console.log("ENV.js loaded::123", API_URL, TASK_SERVICE_API_PORT);
export const TASK_SERVICE_API_URL = `${API_URL}:${TASK_SERVICE_API_PORT}/api`;
export const ROOM_SERVICE_API_URL = `${API_URL}:${ROOM_SERVICE_API_PORT}/api`;
export const USER_SERVICE_API_URL = `${API_URL}:${USER_SERVICE_API_PORT}/api`;
export const AUTH_SERVICE_API_URL = `${API_URL}:${AUTH_SERVICE_API_PORT}/api`;
export const NOTIFICATION_SERVICE_API_URL = `${API_URL}:${NOTIFICATION_SERVICE_API_PORT}/notifications`;
